name: Deploy User Service to AWS

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      LAMBDA_S3_BUCKET: lambda-function-bucket-kienmai
      LAMBDA_FUNCTION_NAME: backend-app-func
      ZIP_FILE_NAME: function.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build backend Lambda
        working-directory: backend-app
        run: |
          npm ci
          npm run build
      - name: Package Lambda function
        working-directory: backend-app/dist
        run: |
          zip -r ../../${ZIP_FILE_NAME} .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload Lambda package to S3
        run: |
          aws s3 cp $ZIP_FILE_NAME s3://$LAMBDA_S3_BUCKET/$ZIP_FILE_NAME
          echo "---> Successfully uploaded $ZIP_FILE_NAME to $LAMBDA_S3_BUCKET"
      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --s3-bucket $LAMBDA_S3_BUCKET \
            --s3-key $ZIP_FILE_NAME
          echo "---> Lambda function '$LAMBDA_FUNCTION_NAME' code updated successfully"
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: Install CDK dependencies
        working-directory: infra-cdk
        run: npm ci
      - name: CDK Bootstrap (if not done yet)
        working-directory: infra-cdk
        run: cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      - name: Deploy CDK Stack
        working-directory: infra-cdk
        run: |
          cdk synth
          cdk deploy --all --require-approval never
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
